environments:
  # Global env vars â€” applied to all environments
  global:
    env:
      - name: PORT
        value: '3000'
      - name: NODE_ENV
        value: 'stage'

  stage:
    containerPort: 3000
    replicas: 1
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      triggers:
        - type: cpu
          utilizationPercentage: 70
        - type: memory
          utilizationPercentage: 80
        - type: http
          requestsPerSecond: 50

