name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: basepartnersense.azurecr.io
  IMAGE_NAME: schedule_visualizer
  CUSTOMER: doc-test
  ENVIRONMENT: stage

jobs:
  build:

    if: github.event_name == 'push'
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Read version
      #   run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: "Run slugify"
        id: slugify
        uses: eltimn/slugify-action@v2.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image to ACR
      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.slugify.outputs.branch }}-${{ steps.slugify.outputs.sha }}
            echo "image_tag=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.slugify.outputs.branch }}-${{ steps.slugify.outputs.sha }}" >> $GITHUB_OUTPUT
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ env.ENVIRONMENT }}

    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Base Platform
        uses: NorceTech/base-actions/deploy@v1
        with:
          environment: ${{ env.ENVIRONMENT }}
          image_tag: ${{ needs.build.outputs.image_tag }}
          customer: ${{ env.CUSTOMER }}
          image: ${{ env.IMAGE_NAME }}
          config_file: .base/config.yaml
          api_url: https://base-api.norce.tech
          api_key: ${{ secrets.BASE_PLATFORM_API_KEY }}
          wait_for_healthy: 'true'
          wait_timeout: '600'
